apiVersion: 1

datasources:
  - name: CardinalSin
    uid: cardinalsin-prom
    type: prometheus
    access: proxy
    url: http://query:8080
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      timeInterval: 10s
